services:
  toggle:
    build: .
    ports:
      - "10800:10800"
    restart: unless-stopped
    environment:
      APP_ENV: production
      MONGODB_URI: mongodb://host.docker.internal:27017
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M